## Prepare notebook for webscraping

This command installs the requests package using the pip package installer for Python. The requests package provides a simple and easy-to-use interface for making HTTP requests to retrieve data from web pages, APIs, and other online resources.

In [6]:
pip install requests

Requirement already satisfied: requests in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (2.30.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from requests) (3.1.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from requests) (2.0.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from requests) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from requests) (2022.12.7)
Note: you may need to restart the kernel to use updated packages.

Import requests to allow us to interact with websites and web APIs by sending HTTP requests and receiving responses.

In [7]:
import requests

Create a list of years from 2013 to 2023 using the range() function.

In [8]:
years = list(range(2013, 2024))

Call the variable *years* to view list

In [9]:
years

[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

Initialize URL variable for scraping NBA season statistics from Basketball-Reference.com

In [10]:
url_start = "https://www.basketball-reference.com/leagues/NBA_{}.html"

Create a folder to store our html code for each website into our working directory

In [11]:
!mkdir nba_stats

mkdir: nba_stats: File exists

## Iterate through a list of years and write NBA season stats to local HTML files

In [12]:
for year in years:
  url = url_start.format(year)
  data = requests.get(url)

  with open("nba_stats/{}.html".format(year), "w+") as f:
    f.write(data.text)

Parse HTML data with BeautifulSoup to extract relevant information for NBA win prediction

In [13]:
pip install bs4

Requirement already satisfied: bs4 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from bs4) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from beautifulsoup4->bs4) (2.4.1)
Note: you may need to restart the kernel to use updated packages.

In [14]:
from bs4 import BeautifulSoup

# Test set

Read HTML content from the 2013 stored file using a with statement and store it in the variable page

In [15]:
with open("nba_stats/2013.html") as f:
  page = f.read()

Parse HTML content using BeautifulSoup and specify the HTML parser to use

In [16]:
soup = BeautifulSoup(page, "html.parser")

Looking at html file, there is an issue with the Per Game Stat table on the BasketballReference page that may cause problems when uploading data to Pandas. Specifically, the table has an additional row that separates the bottom half of the teams, and this row should not be included as a header when uploading the data to Pandas. To address this issue, the code uses BeautifulSoup to locate the specific tr code that has a class named thead and remove it from the HTML content by using the decompose() method. By doing this, we can ensure that the data is formatted correctly and ready for analysis in Pandas.

In [17]:
soup.find('tr', class_= "thead").decompose()

This code line uses BeautifulSoup to find the tfoot element in the HTML content, which represents the footer row of the Per Game Stat table on the BasketballReference page. The decompose() method is then used to remove this row from the HTML content. This is done because the footer row provides league averages, which we do not want to include in our analysis since it is not specific to any individual team. By removing this row, we can ensure that our data is properly structured and ready for analysis in Pandas.

In [18]:
soup.find('tfoot').decompose()

Using BeautifulSoup's find() method, the code will searche for the first element with the given ID attribute. By isolating only the table we need, we can avoid processing unnecessary data and make our code more efficient. The resulting stat_table variable can be used to extract the relevant data for our analysis.

In [24]:
stat_table = soup.find(id="per_game-team")

# Creating a Data Frame

Pandas is a popular Python library for data manipulation and analysis that provides powerful tools for handling data in tabular format. By installing Pandas using the pip command, the code will gain access to the library's functions and data structures, enabling it to easily create, manipulate, and analyze data frames.

In [19]:
pip install pandas

Requirement already satisfied: pandas in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (2.0.1)
Requirement already satisfied: numpy>=1.21.0 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from pandas) (1.24.3)
Requirement already satisfied: pytz>=2020.1 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
import pandas as pd

The read_html() function takes the HTML code as input and returns a list of data frames found on the page. In this case, we are taking the first element of the list ([0]), assuming that it is the only data frame on the page. We then assign this data frame to a variable named stat_2013.

In [21]:
!pip install lxml

Requirement already satisfied: lxml in /Users/fabri/opt/anaconda3/envs/.venv/lib/python3.10/site-packages (4.9.2)

In [22]:
import lxml

Take the first element of the list ([0]) from the tag variable stat_table. We then assign this data frame to a variable named stat_2013.

In [25]:
stat_2013 = pd.read_html(str(stat_table))[0]

In [26]:
stat_2013

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Denver Nuggets*,82,242.7,40.7,85.2,0.478,6.4,18.5,0.343,...,0.701,13.3,31.7,45.0,24.4,9.3,6.5,15.3,20.5,106.1
1,2,Houston Rockets*,82,241.2,38.1,82.7,0.461,10.6,28.9,0.366,...,0.754,11.1,32.3,43.4,23.2,8.3,4.4,16.4,20.3,106.0
2,3,Oklahoma City Thunder*,82,241.8,38.1,79.3,0.481,7.3,19.4,0.377,...,0.828,10.4,33.2,43.6,21.4,8.3,7.6,15.3,20.2,105.7
3,4,San Antonio Spurs*,82,242.4,39.1,81.4,0.481,8.1,21.5,0.376,...,0.791,8.1,33.2,41.3,25.1,8.5,5.4,14.7,17.4,103.0
4,5,Miami Heat*,82,242.4,38.4,77.4,0.496,8.7,22.1,0.396,...,0.754,8.2,30.4,38.6,23.0,8.7,5.4,13.9,18.7,102.9
5,6,Los Angeles Lakers*,82,240.9,37.1,81.0,0.458,8.7,24.6,0.355,...,0.692,11.5,33.3,44.8,22.2,7.0,5.2,15.0,17.9,102.2
6,7,Golden State Warriors*,82,241.5,38.2,83.4,0.458,8.0,19.9,0.403,...,0.790,10.8,34.2,45.0,22.5,6.9,4.2,15.1,21.4,101.2
7,8,Los Angeles Clippers*,82,240.6,38.5,80.6,0.478,7.6,21.4,0.358,...,0.711,11.4,30.2,41.6,23.9,9.6,5.6,14.6,20.9,101.1
8,9,Dallas Mavericks,82,243.7,38.8,84.0,0.462,7.4,19.9,0.372,...,0.793,9.4,32.6,41.9,23.2,7.9,5.5,14.0,20.7,101.1
9,10,Sacramento Kings,82,241.8,37.6,84.2,0.447,7.4,20.5,0.363,...,0.769,11.5,29.1,40.6,20.8,8.2,4.2,14.6,20.9,100.2
10,11,New York Knicks*,82,240.6,36.5,81.6,0.448,10.9,28.9,0.376,...,0.759,10.9,29.7,40.6,19.3,8.2,3.6,12.0,20.1,100.0
11,12,Milwaukee Bucks*,82,241.8,38.1,87.8,0.435,7.3,20.4,0.360,...,0.736,13.0,30.9,44.0,22.9,8.4,6.7,14.1,19.0,98.9
12,13,Utah Jazz,82,242.4,37.1,81.8,0.454,6.2,16.9,0.366,...,0.764,12.1,30.0,42.0,22.7,8.4,6.3,14.8,21.3,98.0
13,14,Atlanta Hawks*,82,242.1,37.6,81.0,0.464,8.6,23.2,0.371,...,0.715,9.2,31.6,40.9,24.5,8.1,4.5,14.9,18.0,98.0
14,15,Portland Trail Blazers,82,242.1,36.7,81.9,0.448,8.2,23.2,0.353,...,0.776,10.7,30.2,40.8,21.8,6.6,4.3,14.7,18.5,97.5
15,16,Toronto Raptors,82,243.7,36.3,81.5,0.446,7.0,20.3,0.343,...,0.788,10.6,29.6,40.2,21.5,7.3,4.8,13.7,22.4,97.2
16,17,Brooklyn Nets*,82,242.1,35.9,79.8,0.450,7.7,21.5,0.357,...,0.731,12.8,30.0,42.8,20.3,7.3,4.8,14.7,18.3,96.9
17,18,Boston Celtics*,81,244.9,37.0,79.7,0.465,6.1,17.2,0.358,...,0.776,8.1,31.3,39.3,22.8,8.2,4.5,14.6,21.2,96.5
18,19,Cleveland Cavaliers,82,240.6,36.5,84.2,0.434,6.7,19.3,0.346,...,0.756,12.2,28.8,41.0,20.7,7.9,4.1,14.0,21.2,96.5
19,20,Minnesota Timberwolves,82,240.6,35.9,81.7,0.439,5.5,18.0,0.305,...,0.742,11.9,30.2,42.0,22.4,8.5,4.7,14.8,18.4,95.7
20,21,Phoenix Suns,82,241.5,37.3,84.4,0.443,5.9,17.7,0.330,...,0.744,11.7,29.9,41.6,22.6,8.0,5.3,15.6,20.6,95.2
21,22,Detroit Pistons,82,241.5,36.3,81.0,0.449,6.3,17.6,0.356,...,0.699,12.1,30.0,42.1,21.2,7.0,4.9,15.1,19.8,94.9
22,23,Indiana Pacers*,81,241.9,35.1,80.6,0.436,6.9,19.7,0.347,...,0.746,12.9,33.0,45.9,20.3,7.2,6.3,15.1,20.0,94.7
23,24,New Orleans Hornets,82,241.2,36.0,80.4,0.448,6.5,18.0,0.363,...,0.776,12.0,29.6,41.6,21.0,6.3,5.4,14.5,20.4,94.1
24,25,Orlando Magic,82,241.2,37.7,84.2,0.448,6.2,18.7,0.329,...,0.755,10.9,31.9,42.7,22.8,6.4,4.4,14.5,19.4,94.1
25,26,Memphis Grizzlies*,82,241.5,36.1,81.5,0.444,4.7,13.5,0.345,...,0.773,12.9,29.8,42.7,20.9,8.6,5.3,14.0,20.2,93.4
26,27,Charlotte Bobcats,82,241.5,34.4,81.1,0.425,5.7,17.1,0.335,...,0.750,11.2,29.1,40.3,19.4,7.2,5.8,14.1,19.0,93.4
27,28,Philadelphia 76ers,82,240.9,37.3,84.1,0.444,6.3,17.5,0.360,...,0.729,10.9,30.4,41.3,22.8,7.4,4.7,13.0,18.4,93.2
28,29,Chicago Bulls*,82,241.8,35.7,81.7,0.437,5.4,15.4,0.353,...,0.773,12.5,30.7,43.2,23.0,7.2,5.1,14.3,19.7,93.2
29,30,Washington Wizards,82,242.1,35.5,81.6,0.435,6.6,18.2,0.365,...,0.733,10.8,32.3,43.2,21.6,7.3,4.6,15.1,20.5,93.2

# Create a dataframe containing all seasons

loop through each year in the years list, opening the corresponding HTML file, using BeautifulSoup to extract the relevant table data, converting it to a Pandas DataFrame, and appending that DataFrame to a list called dfs.

In [27]:
dfs = []

for year in years:
  with open("nba_stats/{}.html".format(year)) as f:
    page = f.read()
  soup = BeautifulSoup(page, "html.parser")
  soup.find('tr', class_="thead").decompose()
  soup.find('tfoot').decompose()
  stat_table = soup.find(id="per_game-team")
  stat_years = pd.read_html(str(stat_table))[0]
  stat_years["Year"] = year

  dfs.append(stat_years)

In [28]:
dfs

[    Rk                    Team   G     MP    FG   FGA    FG%    3P   3PA
 0    1         Denver Nuggets*  82  242.7  40.7  85.2  0.478   6.4  18.5  \
 1    2        Houston Rockets*  82  241.2  38.1  82.7  0.461  10.6  28.9
 2    3  Oklahoma City Thunder*  82  241.8  38.1  79.3  0.481   7.3  19.4
 3    4      San Antonio Spurs*  82  242.4  39.1  81.4  0.481   8.1  21.5
 4    5             Miami Heat*  82  242.4  38.4  77.4  0.496   8.7  22.1
 5    6     Los Angeles Lakers*  82  240.9  37.1  81.0  0.458   8.7  24.6
 6    7  Golden State Warriors*  82  241.5  38.2  83.4  0.458   8.0  19.9
 7    8   Los Angeles Clippers*  82  240.6  38.5  80.6  0.478   7.6  21.4
 8    9        Dallas Mavericks  82  243.7  38.8  84.0  0.462   7.4  19.9
 9   10        Sacramento Kings  82  241.8  37.6  84.2  0.447   7.4  20.5
 10  11        New York Knicks*  82  240.6  36.5  81.6  0.448  10.9  28.9
 11  12        Milwaukee Bucks*  82  241.8  38.1  87.8  0.435   7.3  20.4
 12  13               Utah Jazz  82  242.4  37.1  81.8  0.454   6.2  16.9
 13  14          Atlanta Hawks*  82  242.1  37.6  81.0  0.464   8.6  23.2
 14  15  Portland Trail Blazers  82  242.1  36.7  81.9  0.448   8.2  23.2
 15  16         Toronto Raptors  82  243.7  36.3  81.5  0.446   7.0  20.3
 16  17          Brooklyn Nets*  82  242.1  35.9  79.8  0.450   7.7  21.5
 17  18         Boston Celtics*  81  244.9  37.0  79.7  0.465   6.1  17.2
 18  19     Cleveland Cavaliers  82  240.6  36.5  84.2  0.434   6.7  19.3
 19  20  Minnesota Timberwolves  82  240.6  35.9  81.7  0.439   5.5  18.0
 20  21            Phoenix Suns  82  241.5  37.3  84.4  0.443   5.9  17.7
 21  22         Detroit Pistons  82  241.5  36.3  81.0  0.449   6.3  17.6
 22  23         Indiana Pacers*  81  241.9  35.1  80.6  0.436   6.9  19.7
 23  24     New Orleans Hornets  82  241.2  36.0  80.4  0.448   6.5  18.0
 24  25           Orlando Magic  82  241.2  37.7  84.2  0.448   6.2  18.7
 25  26      Memphis Grizzlies*  82  241.5  36.1  81.5  0.444   4.7  13.5
 26  27       Charlotte Bobcats  82  241.5  34.4  81.1  0.425   5.7  17.1
 27  28      Philadelphia 76ers  82  240.9  37.3  84.1  0.444   6.3  17.5
 28  29          Chicago Bulls*  82  241.8  35.7  81.7  0.437   5.4  15.4
 29  30      Washington Wizards  82  242.1  35.5  81.6  0.435   6.6  18.2

       3P%  ...   ORB   DRB   TRB   AST  STL  BLK   TOV    PF    PTS  Year
 0   0.343  ...  13.3  31.7  45.0  24.4  9.3  6.5  15.3  20.5  106.1  2013
 1   0.366  ...  11.1  32.3  43.4  23.2  8.3  4.4  16.4  20.3  106.0  2013
 2   0.377  ...  10.4  33.2  43.6  21.4  8.3  7.6  15.3  20.2  105.7  2013
 3   0.376  ...   8.1  33.2  41.3  25.1  8.5  5.4  14.7  17.4  103.0  2013
 4   0.396  ...   8.2  30.4  38.6  23.0  8.7  5.4  13.9  18.7  102.9  2013
 5   0.355  ...  11.5  33.3  44.8  22.2  7.0  5.2  15.0  17.9  102.2  2013
 6   0.403  ...  10.8  34.2  45.0  22.5  6.9  4.2  15.1  21.4  101.2  2013
 7   0.358  ...  11.4  30.2  41.6  23.9  9.6  5.6  14.6  20.9  101.1  2013
 8   0.372  ...   9.4  32.6  41.9  23.2  7.9  5.5  14.0  20.7  101.1  2013
 9   0.363  ...  11.5  29.1  40.6  20.8  8.2  4.2  14.6  20.9  100.2  2013
 10  0.376  ...  10.9  29.7  40.6  19.3  8.2  3.6  12.0  20.1  100.0  2013
 11  0.360  ...  13.0  30.9  44.0  22.9  8.4  6.7  14.1  19.0   98.9  2013
 12  0.366  ...  12.1  30.0  42.0  22.7  8.4  6.3  14.8  21.3   98.0  2013
 13  0.371  ...   9.2  31.6  40.9  24.5  8.1  4.5  14.9  18.0   98.0  2013
 14  0.353  ...  10.7  30.2  40.8  21.8  6.6  4.3  14.7  18.5   97.5  2013
 15  0.343  ...  10.6  29.6  40.2  21.5  7.3  4.8  13.7  22.4   97.2  2013
 16  0.357  ...  12.8  30.0  42.8  20.3  7.3  4.8  14.7  18.3   96.9  2013
 17  0.358  ...   8.1  31.3  39.3  22.8  8.2  4.5  14.6  21.2   96.5  2013
 18  0.346  ...  12.2  28.8  41.0  20.7  7.9  4.1  14.0  21.2   96.5  2013
 19  0.305  ...  11.9  30.2  42.0  22.4  8.5  4.7  14.8  18.4   95.7  2013
 20  0.330  ...  11.7  29.9  41.6  22.6  8.0  5.3  15.6  20.6   95.2  2013
 21  0.356  ...  12.1  30.0  42.1  21.2  7.0  4.9  15.1  19.8   94.9  2013
 22  0.347  ...  12.9  33.0  45.9  20.3  7.2  6.3  15.1  20.0   94.7  2013
 23  0.363  ...  12.0  29.6  41.6  21.0  6.3  5.4  14.5  20.4   94.1  2013
 24  0.329  ...  10.9  31.9  42.7  22.8  6.4  4.4  14.5  19.4   94.1  2013
 25  0.345  ...  12.9  29.8  42.7  20.9  8.6  5.3  14.0  20.2   93.4  2013
 26  0.335  ...  11.2  29.1  40.3  19.4  7.2  5.8  14.1  19.0   93.4  2013
 27  0.360  ...  10.9  30.4  41.3  22.8  7.4  4.7  13.0  18.4   93.2  2013
 28  0.353  ...  12.5  30.7  43.2  23.0  7.2  5.1  14.3  19.7   93.2  2013
 29  0.365  ...  10.8  32.3  43.2  21.6  7.3  4.6  15.1  20.5   93.2  2013

 [30 rows x 26 columns],
     Rk                     Team   G     MP    FG   FGA    FG%   3P   3PA
 0    1    Los Angeles Clippers*  82  240.9  39.1  82.5  0.474  8.5  24.0  \
 1    2         Houston Rockets*  82  241.8  38.0  80.5  0.472  9.5  26.6
 2    3   Minnesota Timberwolves  82  242.1  38.9  87.5  0.444  7.3  21.4
 3    4  Portland Trail Blazers*  82  242.1  39.1  87.0  0.450  9.4  25.3
 4    5   Oklahoma City Thunder*  82  241.5  39.0  82.7  0.471  8.1  22.4
 5    6       San Antonio Spurs*  82  240.9  40.6  83.5  0.486  8.5  21.4
 6    7             Phoenix Suns  82  240.9  38.7  83.5  0.463  9.3  25.1
 7    8        Dallas Mavericks*  82  241.8  39.6  83.6  0.474  8.8  22.9
 8    9           Denver Nuggets  82  240.9  38.4  85.9  0.447  8.6  23.9
 9   10   Golden State Warriors*  82  241.8  39.5  85.4  0.462  9.4  24.8
 10  11       Los Angeles Lakers  82  240.3  38.3  85.1  0.450  9.4  24.8
 11  12              Miami Heat*  82  242.4  38.3  76.5  0.501  8.1  22.3
 12  13         Toronto Raptors*  82  243.4  36.5  81.9  0.445  8.7  23.4
 13  14           Atlanta Hawks*  82  241.8  37.3  81.6  0.458  9.4  25.8
 14  15          Detroit Pistons  82  241.2  38.8  86.9  0.447  6.2  19.3
 15  16      Washington Wizards*  82  244.6  38.7  84.4  0.459  7.9  20.8
 16  17         Sacramento Kings  82  241.8  36.9  82.5  0.447  6.0  18.0
 17  18     New Orleans Pelicans  82  242.1  37.8  82.5  0.459  5.9  15.9
 18  19       Philadelphia 76ers  82  242.1  37.9  87.2  0.435  7.0  22.5
 19  20          New York Knicks  82  242.1  36.9  82.2  0.449  9.3  24.9
 20  21           Brooklyn Nets*  82  242.4  35.7  77.9  0.459  8.6  23.4
 21  22      Cleveland Cavaliers  82  243.0  37.0  84.8  0.437  7.1  20.0
 22  23       Charlotte Bobcats*  82  242.7  36.3  82.1  0.442  6.3  17.9
 23  24          Indiana Pacers*  82  241.2  36.0  80.2  0.449  6.7  18.8
 24  25            Orlando Magic  82  243.4  36.9  82.7  0.445  6.9  19.5
 25  26           Boston Celtics  82  240.6  36.5  83.9  0.435  7.0  21.1
 26  27       Memphis Grizzlies*  82  241.5  38.1  82.0  0.464  4.9  14.0
 27  28          Milwaukee Bucks  82  242.4  36.0  82.2  0.438  6.7  18.9
 28  29                Utah Jazz  82  241.2  36.0  81.1  0.444  6.6  19.2
 29  30           Chicago Bulls*  82  243.0  34.7  80.2  0.432  6.2  17.8

       3P%  ...   ORB   DRB   TRB   AST  STL  BLK   TOV    PF    PTS  Year
 0   0.352  ...  10.5  32.5  43.0  24.6  8.6  4.8  13.9  21.5  107.9  2014
 1   0.358  ...  11.2  34.1  45.3  21.4  7.6  5.6  16.1  20.4  107.7  2014
 2   0.341  ...  12.5  32.2  44.7  23.9  8.8  3.6  13.9  18.3  106.9  2014
 3   0.372  ...  12.5  34.0  46.4  23.2  5.5  4.7  13.7  19.2  106.7  2014
 4   0.361  ...  10.8  33.9  44.7  21.9  8.3  6.1  15.3  22.7  106.2  2014
 5   0.397  ...   9.3  34.0  43.3  25.2  7.4  5.1  14.4  18.2  105.4  2014
 6   0.372  ...  11.3  31.7  43.0  19.1  8.4  4.6  15.3  21.9  105.2  2014
 7   0.384  ...  10.2  30.7  40.9  23.6  8.6  4.3  13.5  20.0  104.8  2014
 8   0.358  ...  12.3  33.1  45.4  22.4  7.5  5.6  15.9  23.0  104.4  2014
 9   0.380  ...  10.9  34.4  45.3  23.3  7.8  5.0  15.2  21.8  104.3  2014
 10  0.381  ...   9.1  32.0  41.0  24.5  7.5  5.4  15.1  19.8  103.0  2014
 11  0.364  ...   7.6  29.2  36.9  22.5  8.9  4.5  14.8  19.5  102.2  2014
 12  0.372  ...  11.4  31.1  42.5  21.2  7.0  4.2  14.1  23.0  101.3  2014
 13  0.363  ...   8.7  31.3  40.0  24.9  8.3  4.0  15.3  19.2  101.0  2014
 14  0.321  ...  14.6  30.8  45.4  20.9  8.4  4.8  14.5  20.3  101.0  2014
 15  0.380  ...  10.8  31.4  42.2  23.3  8.1  4.6  14.7  20.4  100.7  2014
 16  0.333  ...  12.1  32.4  44.5  18.9  7.2  3.9  15.2  22.5  100.5  2014
 17  0.373  ...  11.4  30.3  41.7  21.3  7.9  6.4  13.8  22.6   99.7  2014
 18  0.312  ...  11.6  31.2  42.7  21.8  9.3  4.0  16.9  22.5   99.5  2014
 19  0.372  ...  10.6  29.7  40.3  20.0  7.7  4.5  13.0  22.1   98.6  2014
 20  0.369  ...   8.8  29.4  38.1  20.9  8.6  3.8  14.5  21.7   98.5  2014
 21  0.356  ...  12.1  32.1  44.1  21.2  7.1  3.7  14.2  20.0   98.2  2014
 22  0.351  ...   9.5  33.2  42.7  21.7  6.1  5.1  12.3  18.2   96.9  2014
 23  0.357  ...  10.2  34.5  44.7  20.1  6.7  5.4  15.1  20.4   96.7  2014
 24  0.353  ...   9.7  32.4  42.0  21.0  7.7  4.3  14.9  20.5   96.5  2014
 25  0.333  ...  12.0  30.5  42.5  21.0  7.1  4.2  15.4  21.3   96.2  2014
 26  0.353  ...  11.6  30.8  42.4  21.9  7.7  4.6  13.7  19.1   96.1  2014
 27  0.353  ...  11.8  29.3  41.1  21.5  6.6  4.9  15.1  20.9   95.5  2014
 28  0.344  ...  11.0  30.2  41.2  20.3  7.0  4.5  14.6  20.7   95.0  2014
 29  0.348  ...  11.4  32.7  44.1  22.7  7.2  5.2  14.9  19.1   93.7  2014

 [30 rows x 26 columns],
     Rk                     Team   G     MP    FG   FGA    FG%    3P   3PA
 0    1   Golden State Warriors*  82  240.6  41.6  87.0  0.478  10.8  27.0  \
 1    2    Los Angeles Clippers*  82  240.6  39.4  83.3  0.473  10.1  26.9
 2    3        Dallas Mavericks*  82  242.4  39.7  85.8  0.463   8.9  25.4
 3    4    Oklahoma City Thunder  82  241.8  38.8  86.8  0.447   7.7  22.7
 4    5         Toronto Raptors*  82  242.1  37.9  83.3  0.455   8.9  25.1
 5    6         Houston Rockets*  82  241.5  37.0  83.3  0.444  11.4  32.7
 6    7       San Antonio Spurs*  82  243.4  39.1  83.6  0.468   8.3  22.5
 7    8     Cleveland Cavaliers*  82  241.2  37.7  82.2  0.458  10.1  27.5
 8    9  Portland Trail Blazers*  82  242.1  38.7  86.0  0.450   9.8  27.2
 9   10           Atlanta Hawks*  82  240.6  38.1  81.7  0.466  10.0  26.2
 10  11             Phoenix Suns  82  242.4  38.8  85.8  0.452   8.5  25.0
 11  12           Denver Nuggets  82  242.4  37.8  87.3  0.433   8.0  24.8
 12  13          Boston Celtics*  82  242.4  38.9  87.9  0.443   8.0  24.6
 13  14         Sacramento Kings  82  242.1  36.7  80.7  0.455   5.6  16.5
 14  15           Chicago Bulls*  82  242.4  36.6  82.9  0.442   7.9  22.3
 15  16    New Orleans Pelicans*  82  241.2  37.9  82.9  0.457   7.1  19.3
 16  17      Washington Wizards*  82  243.4  38.3  82.8  0.462   6.1  16.8
 17  18       Los Angeles Lakers  82  243.0  37.2  85.6  0.435   6.5  18.9
 18  19          Detroit Pistons  82  241.8  37.1  85.8  0.432   8.6  24.9
 19  20       Memphis Grizzlies*  82  242.7  37.8  82.5  0.458   5.2  15.2
 20  21           Brooklyn Nets*  82  243.0  37.4  83.0  0.451   6.6  19.9
 21  22   Minnesota Timberwolves  82  241.5  36.4  83.2  0.438   5.0  14.9
 22  23         Milwaukee Bucks*  82  243.0  37.6  82.0  0.459   6.6  18.3
 23  24           Indiana Pacers  82  242.1  36.6  83.2  0.439   7.5  21.2
 24  25            Orlando Magic  82  240.9  37.5  82.8  0.453   6.8  19.5
 25  26                Utah Jazz  82  240.3  35.4  79.2  0.447   7.4  21.7
 26  27               Miami Heat  82  240.6  35.2  77.2  0.456   6.8  20.2
 27  28        Charlotte Hornets  82  242.7  35.5  84.5  0.420   6.1  19.1
 28  29       Philadelphia 76ers  82  241.5  33.7  82.6  0.408   8.4  26.3
 29  30          New York Knicks  82  242.1  35.1  82.0  0.428   6.8  19.7

       3P%  ...   ORB   DRB   TRB   AST  STL  BLK   TOV    PF    PTS  Year
 0   0.398  ...  10.4  34.3  44.7  27.4  9.3  6.0  14.5  19.9  110.0  2015
 1   0.376  ...   9.6  33.1  42.6  24.8  7.8  5.0  12.3  21.3  106.7  2015
 2   0.352  ...  10.5  31.8  42.3  22.5  8.1  4.5  13.0  20.0  105.2  2015
 3   0.339  ...  12.8  34.7  47.5  20.5  7.3  5.5  14.7  22.3  104.0  2015
 4   0.352  ...  10.7  30.8  41.5  20.7  7.5  4.4  12.9  20.9  104.0  2015
 5   0.348  ...  11.7  32.0  43.7  22.2  9.5  5.0  16.7  22.0  103.9  2015
 6   0.367  ...   9.8  33.8  43.6  24.4  8.0  5.4  14.0  19.1  103.2  2015
 7   0.367  ...  11.1  31.9  43.0  22.1  7.4  4.1  14.3  18.4  103.1  2015
 8   0.362  ...  10.7  35.1  45.9  21.9  6.4  4.5  13.6  18.2  102.8  2015
 9   0.380  ...   8.7  31.8  40.6  25.7  9.1  4.6  14.2  17.8  102.5  2015
 10  0.341  ...  10.9  32.2  43.2  20.2  8.5  4.7  15.1  21.3  102.4  2015
 11  0.325  ...  12.3  32.4  44.7  21.8  7.8  4.5  14.2  23.0  101.5  2015
 12  0.327  ...  11.1  32.7  43.8  24.5  8.2  3.6  13.8  21.2  101.4  2015
 13  0.341  ...  10.9  33.3  44.2  20.3  6.7  4.0  16.3  20.7  101.3  2015
 14  0.353  ...  11.7  34.0  45.7  21.7  6.3  5.8  14.0  18.2  100.8  2015
 15  0.370  ...  11.5  32.0  43.5  22.0  6.7  6.2  13.3  18.7   99.4  2015
 16  0.360  ...  10.5  34.2  44.7  24.0  7.3  4.6  15.0  20.8   98.5  2015
 17  0.344  ...  11.6  32.3  43.9  20.9  7.0  4.5  13.2  21.2   98.5  2015
 18  0.344  ...  12.8  32.1  44.9  21.6  7.6  4.7  13.4  19.0   98.5  2015
 19  0.339  ...  10.4  32.1  42.6  21.7  8.5  4.2  13.3  19.1   98.3  2015
 20  0.331  ...  10.3  32.0  42.4  20.9  7.0  4.1  13.8  19.3   98.0  2015
 21  0.332  ...  11.6  29.3  40.9  21.6  8.1  4.0  15.0  19.2   97.8  2015
 22  0.363  ...  10.7  31.4  42.1  23.6  9.6  4.9  16.7  22.1   97.8  2015
 23  0.352  ...  10.4  34.4  44.9  21.4  6.2  4.6  14.0  21.2   97.3  2015
 24  0.347  ...  10.0  31.8  41.8  20.6  7.9  3.8  14.9  20.9   95.7  2015
 25  0.343  ...  12.0  31.9  44.0  19.9  7.6  6.0  15.3  19.3   95.1  2015
 26  0.335  ...   9.1  30.0  39.1  19.8  7.8  4.5  14.8  20.0   94.7  2015
 27  0.318  ...  10.0  34.1  44.1  20.2  6.1  5.5  11.9  18.2   94.2  2015
 28  0.320  ...  11.9  30.9  42.9  20.5  9.6  5.9  17.7  21.7   92.0  2015
 29  0.347  ...  10.6  29.8  40.4  21.3  7.0  4.7  14.7  21.6   91.9  2015

 [30 rows x 26 columns],
     Rk                     Team   G     MP    FG   FGA    FG%    3P   3PA
 0    1   Golden State Warriors*  82  242.4  42.5  87.3  0.487  13.1  31.6  \
 1    2   Oklahoma City Thunder*  82  241.8  41.1  86.4  0.476   8.3  23.7
 2    3         Sacramento Kings  82  241.5  40.0  86.4  0.464   8.0  22.4
 3    4         Houston Rockets*  82  241.8  37.7  83.5  0.452  10.7  30.9
 4    5          Boston Celtics*  82  241.2  39.2  89.2  0.439   8.7  26.1
 5    6  Portland Trail Blazers*  82  241.5  38.6  85.9  0.450  10.5  28.5
 6    7    Los Angeles Clippers*  82  241.8  38.3  82.4  0.465   9.7  26.7
 7    8     Cleveland Cavaliers*  82  242.1  38.7  84.0  0.460  10.7  29.6
 8    9       Washington Wizards  82  240.9  39.5  85.8  0.460   8.6  24.2
 9   10       San Antonio Spurs*  82  240.3  40.1  82.9  0.484   7.0  18.5
 10  11       Charlotte Hornets*  82  242.1  37.0  84.4  0.439  10.6  29.4
 11  12           Atlanta Hawks*  82  241.8  38.6  84.4  0.458   9.9  28.4
 12  13         Toronto Raptors*  82  241.2  36.7  81.3  0.451   8.6  23.4
 13  14     New Orleans Pelicans  82  241.2  38.5  85.9  0.448   8.6  23.8
 14  15   Minnesota Timberwolves  82  242.4  37.7  81.3  0.464   5.5  16.4
 15  16        Dallas Mavericks*  82  244.0  37.4  84.1  0.444   9.8  28.6
 16  17          Indiana Pacers*  82  242.4  38.3  85.2  0.450   8.1  23.0
 17  18            Orlando Magic  82  242.7  39.5  86.8  0.455   7.8  22.2
 18  19         Detroit Pistons*  82  242.4  37.9  86.4  0.439   9.0  26.2
 19  20           Denver Nuggets  82  241.8  37.7  85.4  0.442   8.0  23.7
 20  21            Chicago Bulls  82  242.7  38.6  87.4  0.441   7.9  21.4
 21  22             Phoenix Suns  82  240.3  37.2  85.6  0.435   9.0  25.8
 22  23              Miami Heat*  82  241.8  38.4  81.7  0.470   6.1  18.0
 23  24       Memphis Grizzlies*  82  241.8  36.8  83.6  0.440   6.1  18.5
 24  25          Milwaukee Bucks  82  241.8  38.4  82.2  0.467   5.4  15.6
 25  26            Brooklyn Nets  82  240.9  38.2  84.4  0.453   6.5  18.4
 26  27          New York Knicks  82  241.5  36.9  84.0  0.439   7.4  21.5
 27  28                Utah Jazz  82  243.4  36.1  80.4  0.449   8.5  23.9
 28  29       Philadelphia 76ers  82  241.5  36.2  84.0  0.431   9.3  27.5
 29  30       Los Angeles Lakers  82  240.6  35.1  84.8  0.414   7.8  24.6

       3P%  ...   ORB   DRB   TRB   AST   STL  BLK   TOV    PF    PTS  Year
 0   0.416  ...  10.0  36.2  46.2  28.9   8.4  6.1  15.2  20.7  114.9  2016
 1   0.349  ...  13.1  35.6  48.6  23.0   7.4  5.9  15.9  20.6  110.2  2016
 2   0.359  ...  10.6  33.7  44.2  24.5   8.9  4.5  16.2  20.4  106.6  2016
 3   0.347  ...  11.3  31.7  43.1  22.2  10.0  5.2  15.9  21.8  106.5  2016
 4   0.335  ...  11.6  33.3  44.9  24.2   9.2  4.2  13.7  21.9  105.7  2016
 5   0.370  ...  11.6  33.9  45.5  21.3   6.9  4.6  14.6  21.7  105.1  2016
 6   0.364  ...   8.8  33.3  42.0  22.8   8.6  5.6  13.0  21.3  104.5  2016
 7   0.362  ...  10.6  33.9  44.5  22.7   6.7  3.9  13.6  20.3  104.3  2016
 8   0.358  ...   9.1  32.8  41.8  24.5   8.6  3.9  14.5  20.8  104.1  2016
 9   0.375  ...   9.4  34.5  43.9  24.5   8.3  5.9  13.1  17.5  103.5  2016
 10  0.362  ...   9.0  35.0  43.9  21.7   7.3  5.3  12.6  18.1  103.4  2016
 11  0.350  ...   8.3  33.8  42.1  25.6   9.1  5.9  15.0  19.1  102.8  2016
 12  0.370  ...  10.2  33.2  43.4  18.7   7.8  5.5  13.1  19.6  102.7  2016
 13  0.360  ...   9.5  33.1  42.6  22.2   7.7  4.2  13.4  20.9  102.7  2016
 14  0.338  ...  10.0  31.5  41.6  23.4   8.0  4.6  15.0  20.7  102.4  2016
 15  0.344  ...   9.2  33.9  43.1  22.1   6.8  3.7  12.8  19.5  102.3  2016
 16  0.351  ...  10.3  33.9  44.2  21.2   9.0  4.8  14.9  20.0  102.2  2016
 17  0.350  ...  10.3  33.0  43.3  23.6   8.2  5.1  14.1  20.7  102.1  2016
 18  0.345  ...  12.5  33.9  46.3  19.4   7.0  3.7  13.5  19.0  102.0  2016
 19  0.338  ...  11.5  33.1  44.6  22.7   7.4  4.8  14.7  21.0  101.9  2016
 20  0.371  ...  11.1  35.2  46.3  22.8   6.0  5.7  13.9  18.8  101.6  2016
 21  0.348  ...  11.5  33.3  44.8  20.7   7.7  3.8  17.2  22.7  100.9  2016
 22  0.336  ...   9.8  34.3  44.1  20.8   6.7  6.5  14.1  18.3  100.0  2016
 23  0.331  ...  11.2  30.5  41.6  20.7   8.8  4.3  13.3  21.7   99.1  2016
 24  0.345  ...  10.5  31.2  41.7  23.1   8.2  5.8  15.2  20.7   99.0  2016
 25  0.352  ...  10.5  31.9  42.4  22.3   7.6  4.0  14.8  18.0   98.6  2016
 26  0.346  ...  10.4  34.0  44.4  20.5   5.7  5.7  13.4  19.7   98.4  2016
 27  0.355  ...  10.7  32.5  43.2  19.0   7.7  5.2  14.9  20.2   97.7  2016
 28  0.339  ...   9.5  31.8  41.2  21.5   8.3  6.0  16.4  21.7   97.4  2016
 29  0.317  ...  10.7  32.3  43.0  18.0   7.2  4.1  13.7  20.3   97.3  2016

 [30 rows x 26 columns],
     Rk                     Team   G     MP    FG   FGA    FG%    3P   3PA
 0    1   Golden State Warriors*  82  241.2  43.1  87.1  0.495  12.0  31.2  \
 1    2         Houston Rockets*  82  241.2  40.3  87.2  0.462  14.4  40.3
 2    3           Denver Nuggets  82  240.9  41.2  87.7  0.469  10.6  28.8
 3    4     Cleveland Cavaliers*  82  242.4  39.9  84.9  0.470  13.0  33.9
 4    5      Washington Wizards*  82  242.1  41.3  87.0  0.475   9.2  24.8
 5    6    Los Angeles Clippers*  82  240.9  39.5  83.2  0.475  10.3  27.4
 6    7          Boston Celtics*  82  240.9  38.6  85.1  0.454  12.0  33.4
 7    8  Portland Trail Blazers*  82  243.0  39.5  86.1  0.459  10.4  27.7
 8    9             Phoenix Suns  82  241.8  39.9  88.5  0.450   7.5  22.6
 9   10         Toronto Raptors*  82  241.2  39.2  84.4  0.464   8.8  24.3
 10  11   Oklahoma City Thunder*  82  241.5  39.5  87.4  0.452   8.4  25.8
 11  12            Brooklyn Nets  82  240.9  37.8  85.2  0.444  10.7  31.6
 12  13   Minnesota Timberwolves  82  241.5  39.5  84.4  0.467   7.3  21.0
 13  14       San Antonio Spurs*  82  241.5  39.3  83.7  0.469   9.2  23.5
 14  15          Indiana Pacers*  82  242.1  39.3  84.5  0.465   8.6  23.0
 15  16        Charlotte Hornets  82  241.8  37.7  85.4  0.442  10.0  28.6

Concatenate the data frames generated for each year of NBA player stats, resulting in a single data frame df_stats that contains the Per Game Stat table for all years.

In [29]:
df_stats = pd.concat(dfs)
df_stats

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Denver Nuggets*,82,242.7,40.7,85.2,0.478,6.4,18.5,0.343,...,13.3,31.7,45.0,24.4,9.3,6.5,15.3,20.5,106.1,2013
1,2,Houston Rockets*,82,241.2,38.1,82.7,0.461,10.6,28.9,0.366,...,11.1,32.3,43.4,23.2,8.3,4.4,16.4,20.3,106.0,2013
2,3,Oklahoma City Thunder*,82,241.8,38.1,79.3,0.481,7.3,19.4,0.377,...,10.4,33.2,43.6,21.4,8.3,7.6,15.3,20.2,105.7,2013
3,4,San Antonio Spurs*,82,242.4,39.1,81.4,0.481,8.1,21.5,0.376,...,8.1,33.2,41.3,25.1,8.5,5.4,14.7,17.4,103.0,2013
4,5,Miami Heat*,82,242.4,38.4,77.4,0.496,8.7,22.1,0.396,...,8.2,30.4,38.6,23.0,8.7,5.4,13.9,18.7,102.9,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,26,Orlando Magic,82,241.2,40.5,86.3,0.470,10.8,31.1,0.346,...,10.2,33.1,43.2,23.2,7.4,4.7,15.1,20.1,111.4,2023
26,27,Charlotte Hornets,82,241.8,41.3,90.4,0.457,10.7,32.5,0.330,...,11.0,33.5,44.5,25.1,7.7,5.2,14.2,20.3,111.0,2023
27,28,Houston Rockets,82,240.9,40.6,88.9,0.457,10.4,31.9,0.327,...,13.4,32.9,46.3,22.4,7.3,4.6,16.2,20.5,110.7,2023
28,29,Detroit Pistons,82,241.5,39.6,87.1,0.454,11.4,32.4,0.351,...,11.2,31.3,42.4,23.0,7.0,3.8,15.1,22.1,110.3,2023
29,30,Miami Heat*,82,241.5,39.2,85.3,0.460,12.0,34.8,0.344,...,9.7,30.9,40.6,23.8,8.0,3.0,13.5,18.5,109.5,2023

In [30]:
df_stats.to_csv("nba_stats.csv")

# ADVANCED STAT Table

In [31]:
soup.find('tr', class_= "over_header").decompose()

In [32]:
advanced_table= soup.find(id="advanced-team")

In [34]:
advanced_2013 = pd.read_html(str(advanced_table))

In [35]:
advanced_2013

[      Rk                     Team   Age     W     L  PW  PL    MOV   SOS
 0    1.0          Boston Celtics*  27.4  57.0  25.0  57  25   6.52 -0.15  \
 1    2.0     Cleveland Cavaliers*  25.4  51.0  31.0  55  27   5.38 -0.15
 2    3.0      Philadelphia 76ers*  28.2  54.0  28.0  52  30   4.32  0.06
 3    4.0       Memphis Grizzlies*  24.4  51.0  31.0  51  31   3.94 -0.34
 4    5.0         Milwaukee Bucks*  29.8  58.0  24.0  50  32   3.63 -0.02
 5    6.0          Denver Nuggets*  26.6  53.0  29.0  49  33   3.33 -0.29
 6    7.0         New York Knicks*  24.5  47.0  35.0  48  34   2.93  0.06
 7    8.0        Sacramento Kings*  25.4  48.0  34.0  47  35   2.65 -0.35
 8    9.0            Phoenix Suns*  28.1  45.0  37.0  46  36   2.07  0.01
 9   10.0    New Orleans Pelicans*  25.9  42.0  40.0  46  36   1.89 -0.26
 10  11.0   Golden State Warriors*  27.3  44.0  38.0  45  37   1.80 -0.15
 11  12.0         Toronto Raptors*  25.8  41.0  41.0  45  37   1.48  0.12
 12  13.0           Chicago Bulls*  27.5  40.0  42.0  44  38   1.29  0.07
 13  14.0   Oklahoma City Thunder*  22.8  40.0  42.0  44  38   1.09 -0.12
 14  15.0           Brooklyn Nets*  28.0  45.0  37.0  43  39   0.85  0.18
 15  16.0      Los Angeles Lakers*  27.9  43.0  39.0  42  40   0.57 -0.15
 16  17.0    Los Angeles Clippers*  29.7  44.0  38.0  42  40   0.50 -0.19
 17  18.0           Atlanta Hawks*  24.9  41.0  41.0  42  40   0.29  0.02
 18  19.0         Dallas Mavericks  27.8  38.0  44.0  41  41   0.07 -0.22
 19  20.0  Minnesota Timberwolves*  25.8  42.0  40.0  41  41  -0.04 -0.18
 20  21.0              Miami Heat*  27.7  44.0  38.0  40  42  -0.32  0.18
 21  22.0                Utah Jazz  26.5  37.0  45.0  39  43  -0.94 -0.09
 22  23.0       Washington Wizards  26.2  35.0  47.0  38  44  -1.21  0.15
 23  24.0            Orlando Magic  23.1  34.0  48.0  35  47  -2.56  0.17
 24  25.0           Indiana Pacers  24.5  35.0  47.0  33  49  -3.18  0.28
 25  26.0   Portland Trail Blazers  25.1  33.0  49.0  31  51  -4.01  0.05
 26  27.0        Charlotte Hornets  25.3  27.0  55.0  26  56  -6.24  0.35
 27  28.0          Houston Rockets  22.1  22.0  60.0  23  59  -7.85  0.24
 28  29.0          Detroit Pistons  24.1  17.0  65.0  22  60  -8.22  0.49
 29  30.0        San Antonio Spurs  23.9  22.0  60.0  19  63 -10.04  0.22
 30   NaN           League Average  26.3   NaN   NaN  41  41   0.00  0.00

      SRS  ...  FT/FGA  Unnamed: 22  eFG%.1  TOV%.1  DRB%  FT/FGA.1
 0   6.38  ...   0.197          NaN   0.528    11.3  78.5     0.180  \
 1   5.23  ...   0.206          NaN   0.535    14.4  76.3     0.210
 2   4.37  ...   0.250          NaN   0.541    13.0  77.2     0.217
 3   3.60  ...   0.190          NaN   0.526    13.1  75.9     0.206
 4   3.61  ...   0.184          NaN   0.520    10.4  77.8     0.175
 5   3.04  ...   0.194          NaN   0.543    12.2  76.4     0.201
 6   2.99  ...   0.217          NaN   0.536    11.4  77.1     0.210
 7   2.30  ...   0.225          NaN   0.563    12.6  77.2     0.203
 8   2.08  ...   0.191          NaN   0.532    12.9  76.0     0.234
 9   1.63  ...   0.221          NaN   0.543    13.4  77.4     0.212
 10  1.66  ...   0.178          NaN   0.540    12.3  76.0     0.214
 11  1.59  ...   0.201          NaN   0.565    15.3  76.7     0.223
 12  1.37  ...   0.203          NaN   0.544    13.5  77.8     0.197
 13  0.96  ...   0.207          NaN   0.547    14.4  72.9     0.222
 14  1.03  ...   0.208          NaN   0.530    12.2  73.7     0.212
 15  0.43  ...   0.232          NaN   0.535    10.9  76.3     0.171
 16  0.31  ...   0.217          NaN   0.543    11.7  76.6     0.195
 17  0.32  ...   0.200          NaN   0.552    12.4  75.8     0.206
 18 -0.14  ...   0.225          NaN   0.549    11.9  75.5     0.226
 19 -0.22  ...   0.205          NaN   0.540    13.3  74.3     0.225
 20 -0.13  ...   0.224          NaN   0.561    14.5  77.7     0.198
 21 -1.03  ...   0.209          NaN   0.541    10.9  75.2     0.205
 22 -1.06  ...   0.202          NaN   0.540    11.0  76.1     0.194
 23 -2.39  ...   0.227          NaN   0.550    13.1  77.7     0.211
 24 -2.91  ...   0.209          NaN   0.554    13.0  72.2     0.229
 25 -3.96  ...   0.230          NaN   0.563    12.1  74.9     0.217
 26 -5.89  ...   0.195          NaN   0.544    12.5  75.5     0.211
 27 -7.62  ...   0.215          NaN   0.564    11.8  75.8     0.218
 28 -7.73  ...   0.227          NaN   0.557    11.9  74.0     0.231
 29 -9.82  ...   0.170          NaN   0.576    12.0  74.9     0.201
 30  0.00  ...   0.208          NaN   0.545    12.5  76.0     0.208

     Unnamed: 27                       Arena  Attend.  Attend./G
 0           NaN                   TD Garden   766240      18689
 1           NaN  Rocket Mortgage Fieldhouse   777280      18958
 2           NaN          Wells Fargo Center   839261      20470
 3           NaN                 FedEx Forum   707836      17264
 4           NaN                Fiserv Forum   718786      17531
 5           NaN                  Ball Arena   788635      19235
 6           NaN  Madison Square Garden (IV)   795110      19393
 7           NaN             Golden 1 Center   715491      17451
 8           NaN            Footprint Center   699911      17071
 9           NaN        Smoothie King Center   687691      16773
 10          NaN                Chase Center   740624      18064
 11          NaN            Scotiabank Arena   811261      19787
 12          NaN               United Center   841632      20528
 13          NaN               Paycom Center   636903      15534
 14          NaN             Barclays Center   724439      17669
 15          NaN            Crypto.com Arena   763168      18614
 16          NaN            Crypto.com Arena   720543      17574
 17          NaN            State Farm Arena   719787      17556
 18          NaN    American Airlines Center   827282      20178
 19          NaN               Target Center   687510      16769
 20          NaN                   FTX Arena   807190      19688
 21          NaN                Vivint Arena   728240      17762
 22          NaN           Capital One Arena   710481      17329
 23          NaN                Amway Center   728405      17766
 24          NaN       Gainbridge Fieldhouse   641562      15648
 25          NaN                 Moda Center   767374      18716
 26          NaN             Spectrum Center   702052      17123
 27          NaN               Toyota Center   668865      16314
 28          NaN        Little Caesars Arena   759715      18596
 29          NaN                 AT&T Center   694434      15508
 30          NaN                         NaN   739257      17993

 [31 rows x 31 columns]]

In [36]:
dfs_advanced = []

for year in years:
  with open("nba_stats/{}.html".format(year)) as f:
    page = f.read()
  soup = BeautifulSoup(page, "html.parser")
  soup.find('tr', class_="over_header").decompose()
  soup.find('tfoot').decompose()
  advanced_table = soup.find(id="advanced-team")
  advanced_years = pd.read_html(str(advanced_table))[0]
  advanced_years["Year"] = year

  dfs_advanced.append(advanced_years)

In [37]:
dfs_advanced

[      Rk                    Team   Age     W     L  PW  PL   MOV   SOS   SRS
 0    1.0  Oklahoma City Thunder*  26.0  60.0  22.0  64  18  9.21 -0.06  9.15  \
 1    2.0             Miami Heat*  30.3  66.0  16.0  62  20  7.87 -0.84  7.03
 2    3.0   Los Angeles Clippers*  28.8  56.0  26.0  59  23  6.45 -0.02  6.43
 3    4.0      San Antonio Spurs*  28.6  58.0  24.0  58  24  6.40  0.27  6.67
 4    5.0         Denver Nuggets*  26.1  57.0  25.0  55  27  5.09  0.28  5.37
 5    6.0        New York Knicks*  30.2  54.0  28.0  53  29  4.23 -0.50  3.73
 6    7.0      Memphis Grizzlies*  27.0  56.0  26.0  54  28  4.15  0.18  4.32
 7    8.0         Indiana Pacers*  25.7  49.0  32.0  52  29  4.02 -0.69  3.34
 8    9.0        Houston Rockets*  24.4  45.0  37.0  50  32  3.48  0.22  3.69
 9   10.0          Brooklyn Nets*  28.6  49.0  33.0  46  36  1.78 -0.53  1.25
 10  11.0     Los Angeles Lakers*  30.7  45.0  37.0  44  38  1.16  0.32  1.48
 11  12.0  Golden State Warriors*  25.3  47.0  35.0  44  38  0.89  0.42  1.32
 12  13.0          Atlanta Hawks*  27.1  44.0  38.0  42  40  0.40 -0.48 -0.08
 13  14.0          Chicago Bulls*  28.0  45.0  37.0  42  40  0.32 -0.33 -0.02
 14  15.0               Utah Jazz  26.3  43.0  39.0  41  41 -0.09  0.38  0.30
 15  16.0         Boston Celtics*  29.1  41.0  40.0  40  41 -0.22 -0.40 -0.62
 16  17.0        Dallas Mavericks  29.5  41.0  41.0  39  43 -0.60  0.36 -0.24
 17  18.0        Milwaukee Bucks*  26.4  38.0  44.0  37  45 -1.50 -0.33 -1.83
 18  19.0         Toronto Raptors  25.4  34.0  48.0  37  45 -1.48 -0.48 -1.96
 19  20.0  Minnesota Timberwolves  26.4  31.0  51.0  34  48 -2.37  0.54 -1.83
 20  21.0      Washington Wizards  25.4  29.0  53.0  33  49 -2.54 -0.25 -2.78
 21  22.0  Portland Trail Blazers  24.4  33.0  49.0  32  50 -3.17  0.65 -2.53
 22  23.0      Philadelphia 76ers  25.2  34.0  48.0  31  51 -3.34 -0.17 -3.51
 23  24.0         Detroit Pistons  25.3  29.0  53.0  29  53 -3.99 -0.34 -4.33
 24  25.0     New Orleans Hornets  24.0  27.0  55.0  30  52 -3.87  0.75 -3.12
 25  26.0     Cleveland Cavaliers  24.1  24.0  58.0  28  54 -4.68 -0.19 -4.87
 26  27.0        Sacramento Kings  25.6  28.0  54.0  28  54 -4.88  0.62 -4.26
 27  28.0            Phoenix Suns  26.9  25.0  57.0  23  59 -6.46  0.71 -5.75
 28  29.0           Orlando Magic  24.6  20.0  62.0  22  60 -6.99 -0.14 -7.12
 29  30.0       Charlotte Bobcats  24.4  21.0  61.0  17  65 -9.23 -0.06 -9.29
 30   NaN          League Average  26.7   NaN   NaN  41  41  0.00  0.00  0.00

     ...  Unnamed: 22  eFG%.1  TOV%.1  DRB%  FT/FGA.1  Unnamed: 27
 0   ...          NaN   0.469    13.5  73.4     0.197          NaN  \
 1   ...          NaN   0.487    14.8  73.0     0.200          NaN
 2   ...          NaN   0.492    15.4  73.5     0.229          NaN
 3   ...          NaN   0.480    13.7  74.9     0.179          NaN
 4   ...          NaN   0.493    14.3  71.8     0.193          NaN
 5   ...          NaN   0.508    14.8  74.7     0.216          NaN
 6   ...          NaN   0.475    15.2  74.3     0.209          NaN
 7   ...          NaN   0.453    12.9  74.6     0.197          NaN
 8   ...          NaN   0.502    13.5  75.2     0.196          NaN
 9   ...          NaN   0.503    13.1  73.7     0.174          NaN
 10  ...          NaN   0.496    11.9  74.3     0.163          NaN
 11  ...          NaN   0.486    12.4  75.5     0.211          NaN
 12  ...          NaN   0.496    14.2  73.6     0.181          NaN
 13  ...          NaN   0.477    13.2  73.6     0.206          NaN
 14  ...          NaN   0.501    14.0  73.2     0.226          NaN
 15  ...          NaN   0.482    14.2  73.3     0.216          NaN
 16  ...          NaN   0.492    13.3  73.1     0.227          NaN
 17  ...          NaN   0.492    14.4  71.3     0.201          NaN
 18  ...          NaN   0.500    13.6  73.4     0.247          NaN
 19  ...          NaN   0.511    15.0  74.0     0.187          NaN
 20  ...          NaN   0.483    13.7  74.6     0.206          NaN
 21  ...          NaN   0.512    12.5  73.3     0.189          NaN
 22  ...          NaN   0.495    13.7  73.4     0.200          NaN
 23  ...          NaN   0.505    13.1  73.0     0.209          NaN
 24  ...          NaN   0.520    13.1  74.4     0.208          NaN
 25  ...          NaN   0.523    14.4  72.6     0.225          NaN
 26  ...          NaN   0.517    13.6  71.0     0.227          NaN
 27  ...          NaN   0.512    14.2  71.9     0.208          NaN
 28  ...          NaN   0.508    11.8  74.6     0.195          NaN
 29  ...          NaN   0.524    13.2  71.1     0.197          NaN
 30  ...          NaN   0.496    13.7  73.5     0.204          NaN

                          Arena  Attend.  Attend./G  Year
 0      Chesapeake Energy Arena   746323      18203  2013
 1       AmericanAirlines Arena   819290      19983  2013
 2               STAPLES Center   788293      19227  2013
 3                  AT&T Center   755700      18432  2013
 4                 Pepsi Center   730616      17820  2013
 5   Madison Square Garden (IV)   780353      19033  2013
 6                  FedEx Forum   681613      16625  2013
 7      Bankers Life Fieldhouse   626069      15270  2013
 8                Toyota Center   683564      16672  2013
 9              Barclays Center   704702      17188  2013
 10              STAPLES Center   778877      18997  2013
 11                Oracle Arena   794320      19374  2013
 12               Philips Arena   620146      15126  2013
 13               United Center   896944      21877  2013
 14       EnergySolutions Arena   763915      18632  2013
 15                   TD Garden   744960      18624  2013
 16    American Airlines Center   821490      20036  2013
 17   BMO Harris Bradley Center   616469      15036  2013
 18           Air Canada Centre   743936      18145  2013
 19               Target Center   669956      16340  2013
 20              Verizon Center   670070      16343  2013
 21           Rose Garden Arena   813012      19830  2013
 22          Wells Fargo Center   685412      16717  2013
 23  The Palace of Auburn Hills   606094      14685  2013
 24           New Orleans Arena   565930      13803  2013
 25         Quicken Loans Arena   663882      16192  2013
 26           Sleep Train Arena   563743      13750  2013
 27           US Airways Center   632913      15437  2013
 28                Amway Center   722716      17627  2013
 29     Time Warner Cable Arena   628293      15324  2013
 30                         NaN   710653      17346  2013

 [31 rows x 32 columns],
       Rk                     Team   Age     W     L  PW  PL    MOV   SOS
 0    1.0       San Antonio Spurs*  28.9  62.0  20.0  61  21   7.72  0.28  \
 1    2.0    Los Angeles Clippers*  28.1  57.0  25.0  59  23   6.98  0.30
 2    3.0   Oklahoma City Thunder*  26.2  59.0  23.0  58  24   6.34  0.32
 3    4.0              Miami Heat*  30.6  54.0  28.0  54  28   4.76 -0.61
 4    5.0   Golden State Warriors*  26.3  51.0  31.0  54  28   4.80  0.34
 5    6.0          Indiana Pacers*  27.2  56.0  26.0  54  28   4.40 -0.77
 6    7.0         Houston Rockets*  25.4  54.0  28.0  53  29   4.56  0.50
 7    8.0  Portland Trail Blazers*  25.8  54.0  28.0  52  30   3.99  0.45
 8    9.0         Toronto Raptors*  25.6  48.0  34.0  50  32   3.24 -0.69
 9   10.0             Phoenix Suns  26.2  48.0  34.0  48  34   2.63  0.39
 10  11.0   Minnesota Timberwolves  26.3  40.0  42.0  48  34   2.67  0.43
 11  12.0        Dallas Mavericks*  30.6  49.0  33.0  48  34   2.40  0.50
 12  13.0           Chicago Bulls*  28.6  48.0  34.0  47  35   1.85 -0.66
 13  14.0       Memphis Grizzlies*  28.5  50.0  32.0  46  36   1.57  0.61
 14  15.0      Washington Wizards*  26.3  44.0  38.0  45  37   1.27 -0.79
 15  16.0       Charlotte Bobcats*  25.5  43.0  39.0  40  42  -0.22 -0.67
 16  17.0           Atlanta Hawks*  27.5  38.0  44.0  40  42  -0.48 -0.40
 17  18.0          New York Knicks  28.3  37.0  45.0  39  43  -0.79 -0.61
 18  19.0           Brooklyn Nets*  30.0  44.0  38.0  38  44  -1.00 -0.58
 19  20.0           Denver Nuggets  26.0  36.0  46.0  35  47  -2.15  0.75
 20  21.0     New Orleans Pelicans  24.3  34.0  48.0  33  49  -2.71  0.73
 21  22.0         Sacramento Kings  24.9  28.0  54.0  33  49  -2.90  0.82
 22  23.0      Cleveland Cavaliers  24.9  33.0  49.0  32  50  -3.29 -0.57
 23  24.0          Detroit Pistons  24.7  29.0  53.0  31  51  -3.66 -0.48
 24  25.0           Boston Celtics  25.4  25.0  57.0  28  54  -4.46 -0.51
 25  26.0            Orlando Magic  24.6  23.0  59.0  26  56  -5.44 -0.44
 26  27.0       Los Angeles Lakers  26.8  27.0  55.0  25  57  -6.29  0.96
 27  28.0                Utah Jazz  24.5  25.0  57.0  22  60  -7.17  0.91
 28  29.0          Milwaukee Bucks  24.7  15.0  67.0  20  62  -8.18 -0.23
 29  30.0       Philadelphia 76ers  23.4  19.0  63.0  16  66 -10.45 -0.21
 30   NaN           League Average  26.6   NaN   NaN  41  41   0.00  0.00

       SRS  ...  Unnamed: 22  eFG%.1  TOV%.1  DRB%  FT/FGA.1  Unnamed: 27
 0    8.00  ...          NaN   0.482    12.8  76.4     0.184          NaN  \
 1    7.27  ...          NaN   0.484    13.8  72.5     0.222          NaN
 2    6.66  ...          NaN   0.488    13.9  75.6     0.221          NaN
 3    4.15  ...          NaN   0.511    15.8  73.0     0.212          NaN
 4    5.15  ...          NaN   0.477    13.6  76.3     0.224          NaN
 5    3.63  ...          NaN   0.460    12.9  76.8     0.197          NaN
 6    5.06  ...          NaN   0.489    12.5  74.1     0.193          NaN
 7    4.44  ...          NaN   0.488    11.0  74.7     0.194          NaN
 8    2.55  ...          NaN   0.493    14.1  74.9     0.237          NaN
 9    3.02  ...          NaN   0.496    13.9  73.7     0.237          NaN
 10   3.10  ...          NaN   0.518    14.8  74.4     0.177          NaN
 11   2.91  ...          NaN   0.515    14.8  72.7     0.229          NaN
 12   1.20  ...          NaN   0.471    13.7  75.4     0.189          NaN
 13   2.18  ...          NaN   0.497    13.8  75.7     0.199          NaN
 14   0.48  ...          NaN   0.504    15.0  75.7     0.220          NaN
 15  -0.89  ...          NaN   0.491    12.6  77.6     0.183          NaN
 16  -0.88  ...          NaN   0.510    14.0  74.4     0.196          NaN
 17  -1.40  ...          NaN   0.514    14.0  74.3     0.245          NaN
 18  -1.58  ...          NaN   0.509    14.9  72.3     0.236          NaN
 19  -1.40  ...          NaN   0.500    12.8  74.5     0.233          NaN
 20  -1.98  ...          NaN   0.515    13.6  73.8     0.249          NaN
 21  -2.08  ...          NaN   0.512    12.7  76.6     0.234          NaN
 22  -3.86  ...          NaN   0.508    13.0  75.8     0.199          NaN
 23  -4.13  ...          NaN   0.520    13.8  73.4     0.218          NaN
 24  -4.97  ...          NaN   0.505    13.4  74.2     0.227          NaN
 25  -5.88  ...          NaN   0.504    13.0  75.5     0.211          NaN
 26  -5.33  ...          NaN   0.513    12.4  71.0     0.192          NaN
 27  -6.27  ...          NaN   0.518    12.1  74.5     0.227          NaN
 28  -8.41  ...          NaN   0.520    13.2  71.4     0.225          NaN
 29 -10.66  ...          NaN   0.524    14.9  72.4     0.244          NaN
 30   0.00  ...          NaN   0.501    13.6  74.5     0.215          NaN

                          Arena  Attend.  Attend./G  Year
 0                  AT&T Center   755031      18415  2014
 1               STAPLES Center   787692      19212  2014
 2      Chesapeake Energy Arena   746323      18203  2014
 3       AmericanAirlines Arena   811036      19781  2014
 4                 Oracle Arena   803436      19596  2014
 5      Bankers Life Fieldhouse   717542      17501  2014
 6                Toyota Center   743082      18124  2014
 7                  Moda Center   809612      19747  2014
 8            Air Canada Centre   748339      18252  2014
 9            US Airways Center   650739      15872  2014
 10               Target Center   597157      14565  2014
 11    American Airlines Center   817982      19951  2014
 12               United Center   890370      21716  2014
 13                 FedEx Forum   685458      16718  2014
 14              Verizon Center   698068      17026  2014
 15     Time Warner Cable Arena   636268      15519  2014
 16               Philips Arena   587927      14231  2014
 17  Madison Square Garden (IV)   812292      19812  2014
 18             Barclays Center   707331      17252  2014
 19                Pepsi Center   692898      16900  2014
 20        Smoothie King Center   672029      16391  2014
 21           Sleep Train Arena   667949      16291  2014
 22         Quicken Loans Arena   710522      17330  2014
 23  The Palace of Auburn Hills   616005      15025  2014
 24                   TD Garden   742400      18107  2014
 25                Amway Center   666046      16245  2014
 26              STAPLES Center   771974      18829  2014
 27       EnergySolutions Arena   745203      18176  2014
 28   BMO Harris Bradley Center   552067      13465  2014
 29          Wells Fargo Center   568632      13869  2014
 30                         NaN   713714      17407  2014

 [31 rows x 32 columns],
       Rk                     Team   Age     W     L  PW  PL    MOV   SOS
 0    1.0   Golden State Warriors*  26.6  67.0  15.0  65  17  10.10 -0.09  \
 1    2.0    Los Angeles Clippers*  28.8  56.0  26.0  58  24   6.59  0.22
 2    3.0       San Antonio Spurs*  29.8  55.0  27.0  58  24   6.20  0.14
 3    4.0           Atlanta Hawks*  27.8  60.0  22.0  56  26   5.43 -0.68
 4    5.0     Cleveland Cavaliers*  26.9  53.0  29.0  53  29   4.48 -0.40
 5    6.0  Portland Trail Blazers*  27.0  51.0  31.0  53  29   4.23  0.18
 6    7.0         Houston Rockets*  27.6  56.0  26.0  50  32   3.44  0.38
 7    8.0       Memphis Grizzlies*  29.6  55.0  27.0  50  32   3.24  0.38
 8    9.0         Toronto Raptors*  26.1  49.0  33.0  49  33   3.07 -0.62
 9   10.0           Chicago Bulls*  28.8  50.0  32.0  50  32   3.00 -0.46
 10  11.0        Dallas Mavericks*  29.9  50.0  32.0  49  33   2.90  0.46
 11  12.0    Oklahoma City Thunder  25.4  45.0  37.0  47  35   2.18  0.28
 12  13.0    New Orleans Pelicans*  25.3  45.0  37.0  43  39   0.79  0.34
 13  14.0      Washington Wizards*  28.6  46.0  36.0  43  39   0.72 -0.55
 14  15.0         Milwaukee Bucks*  24.6  41.0  41.0  42  40   0.43 -0.52
 15  16.0           Indiana Pacers  28.3  38.0  44.0  42  40   0.28 -0.51
 16  17.0                Utah Jazz  23.4  38.0  44.0  42  40   0.22  0.49
 17  18.0          Boston Celtics*  25.0  40.0  42.0  41  41   0.16 -0.56
 18  19.0             Phoenix Suns  25.7  39.0  43.0  38  44  -0.90  0.52
 19  20.0          Detroit Pistons  25.9  32.0  50.0  38  44  -1.00 -0.39
 20  21.0               Miami Heat  28.5  37.0  45.0  33  49  -2.60 -0.32
 21  22.0           Brooklyn Nets*  28.6  38.0  44.0  33  49  -2.88 -0.25
 22  23.0        Charlotte Hornets  26.0  33.0  49.0  32  50  -3.17 -0.27
 23  24.0           Denver Nuggets  26.4  30.0  52.0  31  51  -3.55  0.48
 24  25.0         Sacramento Kings  26.0  29.0  53.0  31  51  -3.71  0.64
 25  26.0            Orlando Magic  24.3  25.0  57.0  25  57  -5.72 -0.15
 26  27.0       Los Angeles Lakers  27.0  21.0  61.0  23  59  -6.84  0.67
 27  28.0   Minnesota Timberwolves  24.4  16.0  66.0  19  63  -8.79  0.79
 28  29.0       Philadelphia 76ers  23.2  18.0  64.0  18  64  -8.98 -0.07
 29  30.0          New York Knicks  26.9  17.0  65.0  17  65  -9.32 -0.18
 30   NaN           League Average  26.8   NaN   NaN  41  41   0.00  0.00

       SRS  ...  Unnamed: 22  eFG%.1  TOV%.1  DRB%  FT/FGA.1  Unnamed: 27
 0   10.01  ...          NaN   0.470    14.3  74.5     0.217          NaN  \
 1    6.80  ...          NaN   0.493    13.2  75.7     0.231          NaN
 2    6.34  ...          NaN   0.484    13.3  77.3     0.190          NaN
 3    4.75  ...          NaN   0.492    14.9  73.4     0.185          NaN
 4    4.08  ...          NaN   0.502    12.6  74.7     0.177          NaN
 5    4.41  ...          NaN   0.476    11.3  76.2     0.182          NaN
 6    3.82  ...          NaN   0.486    14.6  72.9     0.208          NaN
 7    3.62  ...          NaN   0.492    14.5  75.3     0.183          NaN
 8    2.45  ...          NaN   0.506    13.4  73.3     0.208          NaN
 9    2.54  ...          NaN   0.473    11.3  74.4     0.182          NaN
 10   3.36  ...          NaN   0.503    14.7  72.2     0.204          NaN
 11   2.47  ...          NaN   0.489    12.4  75.6     0.213          NaN
 12   1.13  ...          NaN   0.496    11.7  75.1     0.195          NaN
 13   0.17  ...          NaN   0.481    12.9  77.3     0.210          NaN
 14  -0.09  ...          NaN   0.487    15.9  73.3     0.221          NaN
 15  -0.23  ...          NaN   0.478    12.0  77.9     0.217          NaN
 16   0.71  ...          NaN   0.491    12.8  76.3     0.199          NaN
 17  -0.40  ...          NaN   0.494    13.7  75.0     0.208          NaN
 18  -0.38  ...          NaN   0.497    14.0  73.5     0.221          NaN
 19  -1.39  ...          NaN   0.502    13.2  75.0     0.192          NaN
 20  -2.92  ...          NaN   0.505    14.2  73.4     0.213          NaN
 21  -3.13  ...          NaN   0.506    12.9  73.7     0.185          NaN
 22  -3.44  ...          NaN   0.487    12.0  79.3     0.188          NaN
 23  -3.07  ...          NaN   0.504    13.0  74.7     0.239          NaN
 24  -3.07  ...          NaN   0.507    11.8  75.2     0.200          NaN
 25  -5.87  ...          NaN   0.514    13.6  76.0     0.210          NaN
 26  -6.17  ...          NaN   0.518    12.1  76.3     0.231          NaN
 27  -8.00  ...          NaN   0.537    13.9  71.6     0.187          NaN
 28  -9.04  ...          NaN   0.497    15.2  73.0     0.225          NaN
 29  -9.50  ...          NaN   0.512    13.3  73.1     0.234          NaN
 30   0.00  ...          NaN   0.496    13.3  74.9     0.205          NaN

                          Arena  Attend.  Attend./G  Year
 0                 Oracle Arena   803436      19596  2015
 1               STAPLES Center   785892      19168  2015
 2                  AT&T Center   762855      18606  2015
 3                Philips Arena   713909      17412  2015
 4          Quicken Loans Arena   843042      20562  2015
 5                  Moda Center   798368      19472  2015
 6                Toyota Center   747412      18230  2015
 7                  FedEx Forum   710502      17329  2015
 8            Air Canada Centre   809824      19752  2015
 9                United Center   886612      21625  2015
 10    American Airlines Center   827702      20188  2015
 11     Chesapeake Energy Arena   746323      18203  2015
 12        Smoothie King Center   683757      16677  2015
 13              Verizon Center   747796      18239  2015
 14   BMO Harris Bradley Center   593910      14813  2015
 15     Bankers Life Fieldhouse   691434      16864  2015
 16       EnergySolutions Arena   772059      18831  2015
 17                   TD Garden   721350      17594  2015
 18           US Airways Center   693862      16923  2015
 19  The Palace of Auburn Hills   625917      15266  2015
 20      AmericanAirlines Arena   808223      19713  2015
 21             Barclays Center   698529      17037  2015
 22     Time Warner Cable Arena   704886      17192  2015
 23                Pepsi Center   602707      14700  2015
 24           Sleep Train Arena   680049      16587  2015
 25                Amway Center   688194      16785  2015
 26              STAPLES Center   768244      18738  2015
 27               Target Center   595652      14416  2015
 28          Wells Fargo Center   571572      13941  2015
 29  Madison Square Garden (IV)   812292      19812  2015
 30                         NaN   729877      17814  2015

 [31 rows x 32 columns],
       Rk                     Team   Age     W     L  PW  PL    MOV   SOS
 0    1.0       San Antonio Spurs*  30.3  67.0  15.0  67  15  10.63 -0.36  \

In [38]:
advanced_stats = pd.concat(dfs_advanced)
advanced_stats

,Rk,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,Unnamed: 22,eFG%.1,TOV%.1,DRB%,FT/FGA.1,Unnamed: 27,Arena,Attend.,Attend./G,Year
0,1.0,Oklahoma City Thunder*,26.0,60.0,22.0,64,18,9.21,-0.06,9.15,...,NaN,0.469,13.5,73.4,0.197,NaN,Chesapeake Energy Arena,746323.0,18203.0,2013
1,2.0,Miami Heat*,30.3,66.0,16.0,62,20,7.87,-0.84,7.03,...,NaN,0.487,14.8,73.0,0.200,NaN,AmericanAirlines Arena,819290.0,19983.0,2013
2,3.0,Los Angeles Clippers*,28.8,56.0,26.0,59,23,6.45,-0.02,6.43,...,NaN,0.492,15.4,73.5,0.229,NaN,STAPLES Center,788293.0,19227.0,2013
3,4.0,San Antonio Spurs*,28.6,58.0,24.0,58,24,6.40,0.27,6.67,...,NaN,0.480,13.7,74.9,0.179,NaN,AT&T Center,755700.0,18432.0,2013
4,5.0,Denver Nuggets*,26.1,57.0,25.0,55,27,5.09,0.28,5.37,...,NaN,0.493,14.3,71.8,0.193,NaN,Pepsi Center,730616.0,17820.0,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,27.0,Charlotte Hornets,25.3,27.0,55.0,26,56,-6.24,0.35,-5.89,...,NaN,0.544,12.5,75.5,0.211,NaN,Spectrum Center,702052.0,17123.0,2023
27,28.0,Houston Rockets,22.1,22.0,60.0,23,59,-7.85,0.24,-7.62,...,NaN,0.564,11.8,75.8,0.218,NaN,Toyota Center,668865.0,16314.0,2023
28,29.0,Detroit Pistons,24.1,17.0,65.0,22,60,-8.22,0.49,-7.73,...,NaN,0.557,11.9,74.0,0.231,NaN,Little Caesars Arena,759715.0,18596.0,2023
29,30.0,San Antonio Spurs,23.9,22.0,60.0,19,63,-10.04,0.22,-9.82,...,NaN,0.576,12.0,74.9,0.201,NaN,AT&T Center,694434.0,15508.0,2023
30,NaN,League Average,26.3,NaN,NaN,41,41,0.00,0.00,0.00,...,NaN,0.545,12.5,76.0,0.208,NaN,NaN,739257.0,17993.0,2023

From the advanced_stats ouput we see that there are unnecessary columns and a row called league average. Drop three columns from the advanced_stats dataframe, which are 'Unnamed: 17', 'Unnamed: 22', and 'Unnamed: 27'. Then, a new dataframe called advanced_stats_cleaned is created by selecting only the rows where the 'Team' column is not equal to 'League Average'. This step is done to remove any rows that contain league average stats.

In [39]:
advanced_stats = advanced_stats.drop(columns=['Unnamed: 17','Unnamed: 22','Unnamed: 27'])
advanced_stats_cleaned = advanced_stats.loc[advanced_stats['Team'] != 'League Average']

In [40]:
advanced_stats_cleaned

,Rk,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,ORB%,FT/FGA,eFG%.1,TOV%.1,DRB%,FT/FGA.1,Arena,Attend.,Attend./G,Year
0,1.0,Oklahoma City Thunder*,26.0,60.0,22.0,64,18,9.21,-0.06,9.15,...,26.7,0.280,0.469,13.5,73.4,0.197,Chesapeake Energy Arena,746323.0,18203.0,2013
1,2.0,Miami Heat*,30.3,66.0,16.0,62,20,7.87,-0.84,7.03,...,22.2,0.224,0.487,14.8,73.0,0.200,AmericanAirlines Arena,819290.0,19983.0,2013
2,3.0,Los Angeles Clippers*,28.8,56.0,26.0,59,23,6.45,-0.02,6.43,...,28.8,0.203,0.492,15.4,73.5,0.229,STAPLES Center,788293.0,19227.0,2013
3,4.0,San Antonio Spurs*,28.6,58.0,24.0,58,24,6.40,0.27,6.67,...,20.5,0.204,0.480,13.7,74.9,0.179,AT&T Center,755700.0,18432.0,2013
4,5.0,Denver Nuggets*,26.1,57.0,25.0,55,27,5.09,0.28,5.37,...,31.4,0.216,0.493,14.3,71.8,0.193,Pepsi Center,730616.0,17820.0,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,26.0,Portland Trail Blazers,25.1,33.0,49.0,31,51,-4.01,0.05,-3.96,...,22.4,0.230,0.563,12.1,74.9,0.217,Moda Center,767374.0,18716.0,2023
26,27.0,Charlotte Hornets,25.3,27.0,55.0,26,56,-6.24,0.35,-5.89,...,23.8,0.195,0.544,12.5,75.5,0.211,Spectrum Center,702052.0,17123.0,2023
27,28.0,Houston Rockets,22.1,22.0,60.0,23,59,-7.85,0.24,-7.62,...,30.2,0.215,0.564,11.8,75.8,0.218,Toyota Center,668865.0,16314.0,2023
28,29.0,Detroit Pistons,24.1,17.0,65.0,22,60,-8.22,0.49,-7.73,...,24.9,0.227,0.557,11.9,74.0,0.231,Little Caesars Arena,759715.0,18596.0,2023
29,30.0,San Antonio Spurs,23.9,22.0,60.0,19,63,-10.04,0.22,-9.82,...,25.6,0.170,0.576,12.0,74.9,0.201,AT&T Center,694434.0,15508.0,2023

In [41]:
advanced_stats_cleaned.to_csv("advanced_stats.csv")

Merge the two data sets by Team and the Year

In [42]:
merged_data = pd.merge(df_stats, advanced_stats, on=["Team", "Year"])

Remove the Unnamed, Rk, Arena, Attend., and Attend./G columns

In [43]:
merged_data = merged_data.loc[:, ~merged_data.columns.str.contains('^Unnamed|^Rk|^Arena$|^Attend.$|^Attend./G$|^G$')]

In [44]:
merged_data

,Team,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,...,3PAr,TS%,eFG%,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,DRB%,FT/FGA.1
0,Denver Nuggets*,242.7,40.7,85.2,0.478,6.4,18.5,0.343,34.4,66.6,...,0.217,0.549,0.515,13.6,31.4,0.216,0.493,14.3,71.8,0.193
1,Houston Rockets*,241.2,38.1,82.7,0.461,10.6,28.9,0.366,27.5,53.8,...,0.349,0.564,0.525,14.9,26.4,0.232,0.502,13.5,75.2,0.196
2,Oklahoma City Thunder*,241.8,38.1,79.3,0.481,7.3,19.4,0.377,30.8,60.0,...,0.244,0.580,0.527,14.4,26.7,0.280,0.469,13.5,73.4,0.197
3,San Antonio Spurs*,242.4,39.1,81.4,0.481,8.1,21.5,0.376,31.1,59.9,...,0.264,0.568,0.531,14.0,20.5,0.204,0.480,13.7,74.9,0.179
4,Miami Heat*,242.4,38.4,77.4,0.496,8.7,22.1,0.396,29.6,55.4,...,0.285,0.588,0.552,13.7,22.2,0.224,0.487,14.8,73.0,0.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Orlando Magic,241.2,40.5,86.3,0.470,10.8,31.1,0.346,29.8,55.2,...,0.361,0.573,0.532,13.4,23.8,0.227,0.550,13.1,77.7,0.211
326,Charlotte Hornets,241.8,41.3,90.4,0.457,10.7,32.5,0.330,30.5,57.9,...,0.360,0.550,0.516,12.3,23.8,0.195,0.544,12.5,75.5,0.211
327,Houston Rockets,240.9,40.6,88.9,0.457,10.4,31.9,0.327,30.2,56.9,...,0.359,0.554,0.516,14.0,30.2,0.215,0.564,11.8,75.8,0.218
328,Detroit Pistons,241.5,39.6,87.1,0.454,11.4,32.4,0.351,28.2,54.6,...,0.372,0.561,0.520,13.3,24.9,0.227,0.557,11.9,74.0,0.231
329,Miami Heat*,241.5,39.2,85.3,0.460,12.0,34.8,0.344,27.3,50.5,...,0.408,0.574,0.530,12.4,22.8,0.224,0.561,14.5,77.7,0.198

# Replace the asterisk character in team names

In [45]:
merged_data['Team'] = merged_data['Team'].str.replace('*', '')

In [46]:
merged_data

,Team,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,...,3PAr,TS%,eFG%,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,DRB%,FT/FGA.1
0,Denver Nuggets,242.7,40.7,85.2,0.478,6.4,18.5,0.343,34.4,66.6,...,0.217,0.549,0.515,13.6,31.4,0.216,0.493,14.3,71.8,0.193
1,Houston Rockets,241.2,38.1,82.7,0.461,10.6,28.9,0.366,27.5,53.8,...,0.349,0.564,0.525,14.9,26.4,0.232,0.502,13.5,75.2,0.196
2,Oklahoma City Thunder,241.8,38.1,79.3,0.481,7.3,19.4,0.377,30.8,60.0,...,0.244,0.580,0.527,14.4,26.7,0.280,0.469,13.5,73.4,0.197
3,San Antonio Spurs,242.4,39.1,81.4,0.481,8.1,21.5,0.376,31.1,59.9,...,0.264,0.568,0.531,14.0,20.5,0.204,0.480,13.7,74.9,0.179
4,Miami Heat,242.4,38.4,77.4,0.496,8.7,22.1,0.396,29.6,55.4,...,0.285,0.588,0.552,13.7,22.2,0.224,0.487,14.8,73.0,0.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Orlando Magic,241.2,40.5,86.3,0.470,10.8,31.1,0.346,29.8,55.2,...,0.361,0.573,0.532,13.4,23.8,0.227,0.550,13.1,77.7,0.211
326,Charlotte Hornets,241.8,41.3,90.4,0.457,10.7,32.5,0.330,30.5,57.9,...,0.360,0.550,0.516,12.3,23.8,0.195,0.544,12.5,75.5,0.211
327,Houston Rockets,240.9,40.6,88.9,0.457,10.4,31.9,0.327,30.2,56.9,...,0.359,0.554,0.516,14.0,30.2,0.215,0.564,11.8,75.8,0.218
328,Detroit Pistons,241.5,39.6,87.1,0.454,11.4,32.4,0.351,28.2,54.6,...,0.372,0.561,0.520,13.3,24.9,0.227,0.557,11.9,74.0,0.231
329,Miami Heat,241.5,39.2,85.3,0.460,12.0,34.8,0.344,27.3,50.5,...,0.408,0.574,0.530,12.4,22.8,0.224,0.561,14.5,77.7,0.198

# Wave the merged data as a new csv file

In [48]:
merged_data.to_csv("merged_data.csv", index=False)